// Workshop Compass: chaining between workshops.
// inputs = workshops whose output naturally feeds this one. Used to explain the order
// and to flag a skipped prerequisite. Not every workshop needs inputs.
const CHAIN = {
  problem:        {inputs:['kickoff']},
  stakeholders:   {inputs:['kickoff']},
  lean:           {inputs:['problem']},
  bmc:            {inputs:['vpc','lean']},
  vpc:            {inputs:['jtbd','empathy','persona']},
  vision:         {inputs:['problem','vpc']},
  impact:         {inputs:['vision','okr','nsm']},
  box:            {inputs:['vpc']},
  positioning:    {inputs:['jtbd','vpc']},
  nsm:            {inputs:['vision','metrics']},
  okr:            {inputs:['vision','nsm']},
  horizons:       {inputs:['metrics','positioning']},
  prfaq:          {inputs:['problem','jtbd']},
  persona:        {inputs:['research-plan']},
  jtbd:           {inputs:['research-plan']},
  empathy:        {inputs:['research-plan']},
  journey:        {inputs:['persona','jtbd']},
  'research-plan':{inputs:['assumptions','problem']},
  assumptions:    {inputs:['lean','vpc','problem']},
  ost:            {inputs:['okr','nsm','journey']},
  blueprint:      {inputs:['journey']},
  kano:           {inputs:['persona']},
  hmw:            {inputs:['affinity','journey','ost']},
  mindmap:        {inputs:['problem']},
  affinity:       {inputs:['research-plan','brainwriting']},
  crazy8:         {inputs:['hmw']},
  brainwriting:   {inputs:['hmw']},
  dotvote:        {inputs:['crazy8','brainwriting','affinity']},
  sprint:         {inputs:['problem','assumptions']},
  experiments:    {inputs:['assumptions','dotvote']},
  'impact-effort':{inputs:['dotvote','ost']},
  rice:           {inputs:['impact-effort','okr']},
  moscow:         {inputs:['storymap','impact-effort']},
  storymap:       {inputs:['journey','userflow','dotvote']},
  roadmap:        {inputs:['okr','rice','impact']},
  nnl:            {inputs:['impact-effort','ost']},
  decision:       {inputs:['positioning','experiments']},
  wsjf:           {inputs:['impact','okr']},
  sprintplan:     {inputs:['storymap','moscow']},
  sitemap:        {inputs:['journey','storymap']},
  wireframes:     {inputs:['userflow','storyboard'],},
  userflow:       {inputs:['storymap','journey']},
  storyboard:     {inputs:['jtbd','hmw']},
  prd:            {inputs:['storymap','experiments','decision']},
  raci:           {inputs:['stakeholders','charter']},
  daci:           {inputs:['stakeholders']},
  dependencies:   {inputs:['roadmap','storymap']},
  pi:             {inputs:['roadmap','wsjf','dependencies']},
  program:        {inputs:['pi']},
  premortem:      {inputs:['kickoff','prd']},
  launch:         {inputs:['prd','nsm']},
  sync:           {inputs:['stakeholders','raci']},
  'retro-ssc':    {inputs:['sprintplan']},
  'retro-4l':     {inputs:['launch','sprintplan']},
  'retro-sailboat':{inputs:['okr']},
  health:         {inputs:['charter']},
  postmortem:     {inputs:['launch']},
  metrics:        {inputs:['nsm','launch']},
  ia:             {inputs:['pi','program']},
};
if (typeof module !== 'undefined') module.exports = { CHAIN };
