// Workshop Compass: what each workshop needs before it starts.
//  needs : required inputs, the workshop does not work without them
//  anyOf : groups where one member is enough (customer insight from JTBD or empathy map or persona, for instance)
//  helps : useful if you have it, never blocking
// Used to explain the order, to flag a skipped prerequisite, and to draw dependencies.
const CHAIN = {
  kickoff:        {},
  problem:        {helps:['kickoff']},
  stakeholders:   {helps:['kickoff']},
  charter:        {},
  lean:           {helps:['problem']},
  bmc:            {anyOf:[['vpc','lean']]},
  vpc:            {anyOf:[['jtbd','empathy','persona']]},
  vision:         {needs:['problem'], helps:['vpc']},
  impact:         {anyOf:[['vision','okr','nsm']]},
  box:            {helps:['vpc']},
  positioning:    {anyOf:[['jtbd','vpc']]},
  nsm:            {needs:['vision'], helps:['metrics']},
  okr:            {needs:['vision'], helps:['nsm']},
  horizons:       {helps:['metrics','positioning']},
  prfaq:          {needs:['problem'], helps:['jtbd']},
  persona:        {needs:['research-plan']},
  jtbd:           {needs:['research-plan']},
  empathy:        {helps:['research-plan']},
  journey:        {anyOf:[['persona','jtbd']]},
  'research-plan':{anyOf:[['assumptions','problem']]},
  assumptions:    {anyOf:[['lean','vpc','problem']]},
  ost:            {anyOf:[['okr','nsm']], helps:['journey']},
  blueprint:      {needs:['journey']},
  kano:           {helps:['persona']},
  hmw:            {anyOf:[['affinity','journey','ost']]},
  mindmap:        {helps:['problem']},
  affinity:       {anyOf:[['research-plan','brainwriting']]},
  crazy8:         {needs:['hmw']},
  brainwriting:   {needs:['hmw']},
  dotvote:        {anyOf:[['crazy8','brainwriting','affinity']]},
  sprint:         {needs:['problem'], helps:['assumptions']},
  experiments:    {needs:['assumptions'], helps:['dotvote']},
  'impact-effort':{anyOf:[['dotvote','ost']]},
  rice:           {anyOf:[['impact-effort','ost']], helps:['okr']},
  moscow:         {anyOf:[['storymap','impact-effort']]},
  storymap:       {anyOf:[['journey','userflow']], helps:['dotvote']},
  roadmap:        {needs:['okr'], anyOf:[['rice','impact','impact-effort']]},
  nnl:            {anyOf:[['impact-effort','ost']]},
  decision:       {helps:['positioning','experiments']},
  wsjf:           {helps:['impact','okr']},
  sprintplan:     {anyOf:[['storymap','moscow']]},
  sitemap:        {anyOf:[['journey','storymap']]},
  wireframes:     {needs:['userflow'], helps:['storyboard']},
  userflow:       {anyOf:[['storymap','journey']]},
  storyboard:     {anyOf:[['jtbd','hmw']]},
  prd:            {needs:['storymap'], helps:['experiments','decision']},
  raci:           {needs:['stakeholders'], helps:['charter']},
  daci:           {helps:['stakeholders']},
  dependencies:   {needs:['roadmap'], helps:['storymap']},
  pi:             {needs:['roadmap'], helps:['wsjf','dependencies']},
  program:        {needs:['pi']},
  premortem:      {anyOf:[['kickoff','prd']]},
  launch:         {needs:['prd'], helps:['nsm']},
  sync:           {needs:['stakeholders'], helps:['raci']},
  'retro-ssc':    {helps:['sprintplan']},
  'retro-4l':     {helps:['launch','sprintplan']},
  'retro-sailboat':{helps:['okr']},
  health:         {helps:['charter']},
  postmortem:     {helps:['launch']},
  metrics:        {needs:['nsm'], helps:['launch']},
  ia:             {needs:['pi'], helps:['program']},
};
// every input of a workshop, whatever its level
const chainInputs = id => { const c = CHAIN[id] || {}; return [...(c.needs || []), ...(c.anyOf || []).flat(), ...(c.helps || [])]; };
if (typeof module !== 'undefined') module.exports = { CHAIN, chainInputs };
