// Boussole Ateliers : référentiel (source unique pour le site et le générateur FigJam)
const STAGES = [
  {id:'idee',    name:'Idée / pré-produit',  short:'Idée',       hint:"Rien n'est construit, on cherche le bon problème"},
  {id:'prepmf',  name:'Startup pré-PMF',     short:'Pré-PMF',    hint:'MVP en main, traction encore incertaine'},
  {id:'postpmf', name:'Startup post-PMF',    short:'Post-PMF',   hint:'Traction réelle, il faut structurer'},
  {id:'scale',   name:'Scale-up',            short:'Scale-up',   hint:'Plusieurs équipes, dépendances, besoin de cadence'},
  {id:'mature',  name:'Produit mature',      short:'Mature',     hint:'Portefeuille, legacy, optimisation et renouvellement'},
];
const TEAMS = [
  {id:'xs', name:'1 à 5', size:3}, {id:'s', name:'6 à 15', size:10}, {id:'m', name:'16 à 50', size:30}, {id:'l', name:'50+', size:80},
];
const TRIGGERS = [
  {id:'kickoff',  name:'Lancer un projet ou une feature', hint:'Nouveau chantier, nouvelle équipe'},
  {id:'pivot',    name:'Repositionner ou pivoter',        hint:'Le marché ou la cible ne répond pas'},
  {id:'backlog',  name:'Backlog ingérable',               hint:'Arbitrages flous, tout est prioritaire'},
  {id:'misalign', name:'Équipes ou stakeholders désalignés', hint:'Chacun a sa version de la stratégie'},
  {id:'slow',     name:'Delivery lente ou chaotique',     hint:'Dépendances, rituels qui tournent à vide'},
  {id:'growth',   name:'Croissance qui ralentit',         hint:'Chercher le prochain levier'},
  {id:'refonte',  name:'Refonte d\'un produit existant',  hint:'Legacy, parcours usés, dette UX'},
];
const GOALS = [
  {id:'vision',  name:'Vision & stratégie'},
  {id:'users',   name:'Connaissance utilisateurs'},
  {id:'ideas',   name:'Générer des solutions'},
  {id:'prio',    name:'Prioriser'},
  {id:'design',  name:'Concevoir l\'expérience'},
  {id:'align',   name:'Aligner les parties prenantes'},
  {id:'process', name:'Façon de travailler'},
  {id:'measure', name:'Mesurer l\'impact'},
];
const HORIZONS = [
  {id:'demi', name:'Un atelier (2 à 4 h)', cap:2},
  {id:'semaine', name:'Une semaine (3 à 5 ateliers)', cap:5},
  {id:'programme', name:'Programme 6 à 8 semaines', cap:10},
];
const PHASES = [
  {id:'cadrage',    name:'Cadrage & kick-off',        h:'--h-cadrage'},
  {id:'strategie',  name:'Stratégie & vision',        h:'--h-strategie'},
  {id:'research',   name:'Research & discovery',      h:'--h-research'},
  {id:'ideation',   name:'Idéation',                  h:'--h-ideation'},
  {id:'prio',       name:'Priorisation & planification', h:'--h-prio'},
  {id:'conception', name:'Conception',                h:'--h-conception'},
  {id:'alignement', name:'Alignement & delivery',     h:'--h-alignement'},
  {id:'mesure',     name:'Mesure & amélioration continue', h:'--h-mesure'},
];

/* fit = [idée, pré-PMF, post-PMF, scale-up, mature] de 0 (hors sujet) à 3 (central) */
const T = [
 // Cadrage
 {id:'kickoff', name:'Kick-off canvas', phase:'cadrage', fit:[2,2,3,3,3], goals:['align'], triggers:['kickoff','refonte'],
  desc:'Une page pour cadrer le chantier : objectif, définition du succès, périmètre et hors-périmètre, risques, rôles, jalons.',
  why:'Avant tout atelier de fond, tout le monde doit répondre pareil à "pourquoi ce projet et à quoi ressemble la réussite".', dur:2, who:'PM, lead tech, design, sponsor', out:'Charte projet signée par le sponsor'},
 {id:'problem', name:'Problem statement canvas', phase:'cadrage', fit:[3,3,2,2,2], goals:['vision','users'], triggers:['kickoff','pivot','refonte'],
  desc:'Formuler le problème avant la solution : qui souffre, de quoi, pourquoi maintenant, ce qu\'on sait, ce qu\'on suppose.',
  why:'Une équipe qui démarre par la solution passe des semaines à la défendre. Le problème écrit en une phrase évite ça.', dur:1.5, who:'Équipe produit + 1 ou 2 métiers', out:'Énoncé du problème validé + liste des hypothèses'},
 {id:'stakeholders', name:'Stakeholder map (pouvoir / intérêt)', phase:'cadrage', fit:[1,1,2,3,3], goals:['align'], triggers:['kickoff','misalign','refonte'],
  desc:'Positionner chaque partie prenante sur deux axes, décider qui informer, consulter, impliquer.',
  why:'Plus la boîte grossit, plus un chantier meurt d\'un stakeholder oublié que d\'un mauvais choix technique.', dur:1, who:'PM + sponsor', out:'Plan de communication par stakeholder'},
 {id:'charter', name:'Team charter / accords d\'équipe', phase:'cadrage', fit:[2,2,3,3,2], goals:['align','process'], triggers:['kickoff','misalign','slow'],
  desc:'Mission de l\'équipe, valeurs, règles de fonctionnement, rituels, définition de "terminé".',
  why:'Une équipe nouvelle ou recomposée a besoin d\'expliciter ses règles avant de se disputer dessus.', dur:2, who:'Toute l\'équipe', out:'Accords d\'équipe affichés'},
 // Stratégie
 {id:'lean', name:'Lean Canvas', phase:'strategie', fit:[3,3,1,0,0], goals:['vision'], triggers:['kickoff','pivot'],
  desc:'Problème, segments, proposition de valeur unique, solution, canaux, revenus, coûts, métriques, avantage déloyal.',
  why:'Tant que le PMF n\'est pas là, le modèle change toutes les six semaines : une page à réécrire vaut mieux qu\'un business plan.', dur:2, who:'Fondateurs + PM', out:'Canvas v1 + hypothèses les plus risquées identifiées'},
 {id:'bmc', name:'Business Model Canvas', phase:'strategie', fit:[2,2,3,2,2], goals:['vision'], triggers:['pivot','growth'],
  desc:'Les neuf blocs du modèle économique : partenaires, activités, ressources, valeur, relation client, canaux, segments, coûts, revenus.',
  why:'Une fois la traction là, il faut voir comment l\'argent circule vraiment pour choisir où investir.', dur:3, who:'Direction + produit + finance', out:'Modèle partagé, zones de fragilité marquées'},
 {id:'vpc', name:'Value Proposition Canvas', phase:'strategie', fit:[3,3,2,1,2], goals:['vision','users'], triggers:['pivot','kickoff','growth'],
  desc:'Profil client (tâches, douleurs, gains) face à la proposition (produits, soulageurs de douleur, créateurs de gain).',
  why:'Le test le plus rapide de l\'adéquation problème-solution : si les deux moitiés ne se répondent pas, le reste ne sert à rien.', dur:2, who:'Produit + ventes ou support', out:'Fit explicite ou écarts à combler'},
 {id:'vision', name:'Product Vision Board', phase:'strategie', fit:[2,2,3,3,2], goals:['vision'], triggers:['kickoff','misalign','pivot'],
  desc:'Vision, groupe cible, besoins, produit, objectifs business sur une seule planche.',
  why:'Quand plusieurs personnes portent le produit, la vision doit tenir sur un mur, pas dans la tête du fondateur.', dur:2, who:'Direction + leads', out:'Vision partagée en une phrase + 4 blocs'},
 {id:'impact', name:'Impact mapping', phase:'strategie', fit:[1,2,3,3,3], goals:['vision','prio','measure'], triggers:['kickoff','backlog','growth'],
  desc:'Objectif mesurable → acteurs → impacts attendus → livrables. Un arbre qui relie chaque feature à un résultat.',
  why:'Le meilleur outil pour couper ce qui ne sert aucun objectif. Chaque branche sans impact clair disparaît.', dur:3, who:'Produit, tech, métier', out:'Carte d\'impact, livrables reliés à un objectif'},
 {id:'box', name:'Product Box', phase:'strategie', fit:[2,2,2,1,1], goals:['vision','ideas'], triggers:['kickoff','pivot'],
  desc:'Chaque groupe dessine la boîte du produit : nom, promesse, trois arguments, ce qu\'il y a au dos.',
  why:'Force à formuler la promesse en langage client et révèle vite si l\'équipe ne vend pas la même chose.', dur:1.5, who:'Équipe élargie, 3 à 4 groupes', out:'Promesse produit en langage client'},
 {id:'positioning', name:'Carte de positionnement (2x2 concurrentiel)', phase:'strategie', fit:[2,2,3,2,3], goals:['vision'], triggers:['pivot','growth'],
  desc:'Placer les concurrents et soi-même sur deux axes qui comptent pour le client, chercher l\'espace vide.',
  why:'Pour repositionner ou relancer la croissance, il faut voir où l\'on est perçu, pas où l\'on croit être.', dur:1.5, who:'Produit + marketing + ventes', out:'Positionnement cible et message différenciant'},
 {id:'nsm', name:'North Star Metric & arbre de métriques', phase:'strategie', fit:[0,2,3,3,3], goals:['measure','vision'], triggers:['growth','misalign','kickoff'],
  desc:'Choisir la métrique qui reflète la valeur livrée, puis la décomposer en leviers que chaque équipe peut bouger.',
  why:'Sans métrique commune, chaque équipe optimise son coin. L\'arbre relie le travail quotidien à la valeur.', dur:3, who:'Direction, produit, data', out:'NSM + 3 à 5 métriques d\'entrée par équipe'},
 {id:'okr', name:'OKR trimestriels', phase:'strategie', fit:[0,1,3,3,3], goals:['vision','align','measure'], triggers:['misalign','growth','backlog'],
  desc:'Objectifs qualitatifs et résultats clés mesurables, alignés du niveau entreprise à chaque équipe.',
  why:'Passé une équipe, la priorisation ne peut plus se faire de vive voix. Les OKR donnent le cadre d\'arbitrage.', dur:3, who:'Leads de chaque équipe', out:'3 objectifs, 2 à 4 KR chacun, par équipe'},
 {id:'horizons', name:'Three Horizons (portefeuille)', phase:'strategie', fit:[0,0,1,2,3], goals:['vision'], triggers:['growth','refonte'],
  desc:'Répartir les initiatives entre coeur de métier (H1), extensions (H2) et paris (H3), et l\'investissement qui va avec.',
  why:'Un produit mature meurt de sous-investir H2 et H3. Ce cadre rend l\'arbitrage visible au comité de direction.', dur:2, who:'Direction + leads produit', out:'Portefeuille réparti avec budget par horizon'},
 {id:'prfaq', name:'PR/FAQ (working backwards)', phase:'strategie', fit:[2,2,2,3,3], goals:['vision','align'], triggers:['kickoff','refonte'],
  desc:'Écrire le communiqué de presse du lancement et la FAQ avant de construire quoi que ce soit.',
  why:'Dans une grande structure, le document écrit dépasse le pitch : il expose les trous du raisonnement avant l\'investissement.', dur:4, who:'PM rédige, leads relisent', out:'PR/FAQ validé ou projet abandonné à temps'},
 // Research
 {id:'persona', name:'Persona', phase:'research', fit:[2,3,2,2,2], goals:['users'], triggers:['kickoff','refonte','pivot'],
  desc:'Archétype d\'utilisateur construit sur des entretiens : contexte, objectifs, frustrations, comportements.',
  why:'Utile seulement si nourri par des entretiens réels. Sinon c\'est une fiche de personnage.', dur:2, who:'Design + PM + support', out:'2 à 3 personas sourcés'},
 {id:'jtbd', name:'Jobs to be done', phase:'research', fit:[3,3,3,2,3], goals:['users','vision'], triggers:['pivot','growth','kickoff'],
  desc:'Quel progrès le client cherche à faire, dans quelle situation, avec quels critères de réussite.',
  why:'Le seul cadre de research qui reste valable du pré-produit au produit mature : le job ne change pas, la solution oui.', dur:2.5, who:'Produit + design + quelques clients en amont', out:'Job statements + forces de changement'},
 {id:'empathy', name:'Empathy map', phase:'research', fit:[3,3,2,1,1], goals:['users'], triggers:['kickoff','refonte'],
  desc:'Ce que l\'utilisateur dit, pense, fait, ressent, et ce qu\'il gagne ou souffre.',
  why:'Un premier pas rapide quand l\'équipe n\'a jamais rencontré ses utilisateurs.', dur:1, who:'Toute l\'équipe', out:'Carte par segment + questions ouvertes'},
 {id:'journey', name:'Customer journey map', phase:'research', fit:[1,2,3,3,3], goals:['users','design'], triggers:['refonte','growth','kickoff'],
  desc:'Étapes, actions, émotions, points de contact et points de friction du parcours de bout en bout.',
  why:'Une fois qu\'un vrai parcours existe, ses frictions valent plus que dix idées de features.', dur:3, who:'Produit, design, support, ventes', out:'Parcours annoté, top 5 des frictions'},
 {id:'research-plan', name:'Plan de recherche & guide d\'entretien', phase:'research', fit:[3,3,2,2,2], goals:['users'], triggers:['kickoff','pivot','refonte'],
  desc:'Questions de recherche, hypothèses, méthode, recrutement, script d\'entretien non directif.',
  why:'Cinq entretiens bien préparés valent cinquante réponses de sondage. Le plan évite les questions orientées.', dur:1.5, who:'Design + PM', out:'Plan + guide d\'entretien prêt à l\'emploi'},
 {id:'assumptions', name:'Assumption mapping (désirabilité, faisabilité, viabilité)', phase:'research', fit:[3,3,3,2,2], goals:['users','prio'], triggers:['kickoff','pivot'],
  desc:'Lister toutes les hypothèses, les placer sur importance × niveau de preuve, tester d\'abord les plus risquées.',
  why:'Le chaînon manquant entre la vision et la research : il dit quoi aller vérifier en premier.', dur:2, who:'Produit, tech, design', out:'Hypothèses classées, plan de tests'},
 {id:'ost', name:'Opportunity Solution Tree', phase:'research', fit:[1,2,3,3,3], goals:['users','ideas','prio'], triggers:['growth','backlog','kickoff'],
  desc:'Résultat visé → opportunités (besoins, douleurs) → solutions → expériences. L\'arbre de la discovery continue.',
  why:'Structure la discovery quand elle devient continue : l\'équipe voit pourquoi elle explore telle solution et pas une autre.', dur:2.5, who:'Trio PM, design, tech lead', out:'Arbre vivant, opportunité cible du trimestre'},
 {id:'blueprint', name:'Service blueprint', phase:'research', fit:[0,1,2,3,3], goals:['design','align'], triggers:['refonte','slow'],
  desc:'Le parcours client en face des actions visibles, des actions en coulisses et des systèmes qui les supportent.',
  why:'Quand la friction vient de l\'organisation et pas de l\'écran, il faut voir les coulisses.', dur:4, who:'Produit, ops, support, tech', out:'Blueprint + goulots d\'étranglement internes'},
 {id:'kano', name:'Modèle Kano', phase:'research', fit:[0,1,2,2,3], goals:['prio','users'], triggers:['backlog','growth'],
  desc:'Classer les features en basiques, performantes, attractives ou indifférentes via un questionnaire client.',
  why:'Sur un produit mature, le backlog est plein de "basiques" que personne ne remarquera. Kano les distingue des vrais différenciateurs.', dur:2, who:'Produit + panel clients', out:'Classement Kano du backlog'},
 // Idéation
 {id:'hmw', name:'How Might We', phase:'ideation', fit:[3,3,3,2,2], goals:['ideas'], triggers:['kickoff','growth','refonte'],
  desc:'Reformuler chaque insight de research en question "Comment pourrions-nous…" ouverte mais cadrée.',
  why:'Le pont entre research et idéation : sans HMW, le brainstorm repart des opinions au lieu des insights.', dur:1, who:'Équipe produit', out:'5 à 10 questions HMW votées'},
 {id:'mindmap', name:'Mind map', phase:'ideation', fit:[3,2,2,1,1], goals:['ideas'], triggers:['kickoff','pivot'],
  desc:'Explorer un sujet en arborescence, sans jugement, pour cartographier l\'espace du possible.',
  why:'Utile au tout début pour élargir avant de converger. Perd sa valeur dès que le cadre est posé.', dur:1, who:'Petit groupe', out:'Carte des pistes'},
 {id:'affinity', name:'Affinity map', phase:'ideation', fit:[2,3,3,2,2], goals:['users','ideas'], triggers:['kickoff','refonte','growth'],
  desc:'Regrouper des centaines de notes (verbatims, idées) en thèmes émergents, puis nommer les thèmes.',
  why:'La méthode de synthèse après une série d\'entretiens ou un brainstorm large.', dur:2, who:'Ceux qui ont mené la research', out:'Thèmes nommés et hiérarchisés'},
 {id:'crazy8', name:'Crazy 8\'s', phase:'ideation', fit:[2,3,3,2,2], goals:['ideas','design'], triggers:['kickoff','refonte'],
  desc:'Huit esquisses en huit minutes, chacun de son côté, puis partage.',
  why:'Sort l\'équipe de la première idée. Le volume tue le perfectionnisme.', dur:0.75, who:'Toute l\'équipe, y compris non-designers', out:'Esquisses à voter'},
 {id:'brainwriting', name:'Brainwriting 6-3-5', phase:'ideation', fit:[2,2,2,2,2], goals:['ideas'], triggers:['growth','kickoff'],
  desc:'Six personnes, trois idées, cinq minutes, puis on passe la feuille. Silence obligatoire.',
  why:'Évite que les deux voix les plus fortes dictent le brainstorm.', dur:0.75, who:'6 personnes par table', out:'108 idées brutes'},
 {id:'dotvote', name:'Dot voting', phase:'ideation', fit:[2,2,2,2,2], goals:['ideas','prio'], triggers:['kickoff','backlog','growth'],
  desc:'Chacun dispose de N gommettes pour converger sur les idées à creuser.',
  why:'La convergence la plus rapide qui existe. À utiliser après chaque phase divergente.', dur:0.25, who:'Les participants de l\'atelier', out:'Top 3 à creuser'},
 {id:'sprint', name:'Design Sprint (5 jours)', phase:'ideation', fit:[3,3,2,2,2], goals:['ideas','design','users'], triggers:['kickoff','pivot','refonte'],
  desc:'Lundi cartographier, mardi esquisser, mercredi décider, jeudi prototyper, vendredi tester avec 5 utilisateurs.',
  why:'Quand la question est grosse et l\'incertitude haute, cinq jours de sprint évitent trois mois de construction.', dur:35, who:'6 à 7 personnes + un décideur', out:'Prototype testé, décision go / no-go'},
 {id:'experiments', name:'Experiment board / hypothèses', phase:'ideation', fit:[3,3,3,2,2], goals:['measure','ideas'], triggers:['pivot','growth','kickoff'],
  desc:'Hypothèse, test, métrique, critère de succès, résultat, apprentissage. Une ligne par expérience.',
  why:'Transforme les idées en tests bon marché avant de les construire. Le tableau garde la mémoire des apprentissages.', dur:1.5, who:'Trio produit', out:'3 expériences planifiées avec critères'},
 // Priorisation
 {id:'impact-effort', name:'Matrice impact / effort', phase:'prio', fit:[2,3,3,3,3], goals:['prio'], triggers:['backlog','growth','kickoff'],
  desc:'Quatre quadrants : quick wins, gros projets, tâches de remplissage, à éviter.',
  why:'Le premier tri quand le backlog déborde. Trente minutes suffisent pour éliminer la moitié des sujets.', dur:1, who:'Produit + tech lead', out:'Backlog trié en 4 quadrants'},
 {id:'rice', name:'Scoring RICE', phase:'prio', fit:[0,1,3,3,3], goals:['prio'], triggers:['backlog'],
  desc:'Reach × Impact × Confidence ÷ Effort. Un score comparable pour chaque initiative.',
  why:'Quand la matrice impact/effort ne suffit plus parce qu\'il y a trop de candidats et trop de demandeurs.', dur:2, who:'PM + tech + data', out:'Backlog scoré et défendable'},
 {id:'moscow', name:'MoSCoW', phase:'prio', fit:[1,2,3,2,2], goals:['prio'], triggers:['kickoff','backlog'],
  desc:'Must, Should, Could, Won\'t : le périmètre d\'une version en quatre colonnes.',
  why:'Idéal pour cadrer un lot avec un client ou un sponsor qui veut tout.', dur:1.5, who:'Produit + sponsor', out:'Périmètre v1 verrouillé'},
 {id:'storymap', name:'User story map', phase:'prio', fit:[2,3,3,3,2], goals:['prio','design'], triggers:['kickoff','refonte','backlog'],
  desc:'Le parcours en colonnes, les stories en dessous, une ligne horizontale qui découpe les releases.',
  why:'Le meilleur outil pour découper un MVP qui reste cohérent de bout en bout au lieu d\'un empilement de features.', dur:3, who:'Équipe complète', out:'Carte + tranche MVP identifiée'},
 {id:'roadmap', name:'Product roadmap', phase:'prio', fit:[1,2,3,3,3], goals:['prio','align'], triggers:['misalign','backlog','growth'],
  desc:'Initiatives dans le temps, reliées aux objectifs, avec le niveau de confiance.',
  why:'Communique les choix aux autres équipes. Sans objectifs en face, ce n\'est qu\'une liste de promesses datées.', dur:2, who:'Produit + leads', out:'Roadmap par objectif, partagée'},
 {id:'nnl', name:'Now / Next / Later', phase:'prio', fit:[1,3,3,3,2], goals:['prio','align'], triggers:['backlog','misalign'],
  desc:'Trois colonnes sans dates : ce qu\'on fait, ce qui suit, ce qu\'on garde en vue.',
  why:'La roadmap honnête quand l\'incertitude est haute : elle dit l\'ordre sans mentir sur les dates.', dur:1.5, who:'Produit + leads', out:'Roadmap sans dates partagée'},
 {id:'decision', name:'Matrice de décision pondérée', phase:'prio', fit:[1,2,2,3,3], goals:['prio'], triggers:['backlog'],
  desc:'Options en lignes, critères pondérés en colonnes, un score par option.',
  why:'Pour trancher entre deux ou trois grandes options structurantes, pas pour trier un backlog.', dur:1.5, who:'Décideurs + experts', out:'Option retenue et justifiée'},
 {id:'wsjf', name:'WSJF / coût du délai', phase:'prio', fit:[0,0,1,3,3], goals:['prio'], triggers:['backlog','slow'], minTeam:16,
  desc:'(Valeur + urgence + réduction de risque) ÷ taille du travail. La priorisation SAFe.',
  why:'À l\'échelle, avec plusieurs équipes en concurrence sur la même capacité, il faut un critère commun et chiffré.', dur:2, who:'Product managers + architectes', out:'Backlog programme ordonné'},
 {id:'sprintplan', name:'Sprint planning', phase:'prio', fit:[1,2,3,3,2], goals:['process'], triggers:['slow'],
  desc:'Objectif de sprint, capacité, sélection et découpage des stories.',
  why:'Un sprint sans objectif explicite finit en liste de tâches. L\'atelier remet le résultat au centre.', dur:2, who:'Équipe de delivery', out:'Sprint goal + engagement'},
 // Conception
 {id:'sitemap', name:'Sitemap', phase:'conception', fit:[1,2,2,2,3], goals:['design'], triggers:['refonte','kickoff'],
  desc:'Arborescence des écrans et sections, hiérarchie de navigation.',
  why:'Dans une refonte, la structure de l\'information est souvent le vrai problème, pas le visuel.', dur:2, who:'Design + PM', out:'Arborescence cible'},
 {id:'wireframes', name:'Wireframes basse fidélité', phase:'conception', fit:[2,3,3,2,2], goals:['design'], triggers:['kickoff','refonte'],
  desc:'Écrans en gris, sans style, pour valider structure et contenu avant le design.',
  why:'Discuter sur un gris permet de parler de logique sans se perdre dans les couleurs.', dur:3, who:'Design + PM + tech', out:'Écrans clés validés'},
 {id:'userflow', name:'User flow', phase:'conception', fit:[2,3,3,3,3], goals:['design'], triggers:['kickoff','refonte'],
  desc:'Chemin écran par écran, décisions, cas d\'erreur, états vides.',
  why:'Les cas d\'erreur et les états vides représentent la moitié du travail de dev. Le flow les fait apparaître avant le sprint.', dur:2, who:'Design + tech', out:'Flow complet avec cas limites'},
 {id:'storyboard', name:'Storyboard', phase:'conception', fit:[3,2,1,1,1], goals:['design','ideas'], triggers:['kickoff','pivot'],
  desc:'Le scénario d\'usage en six à huit cases dessinées, du contexte au résultat.',
  why:'Avant qu\'un produit existe, raconter l\'histoire teste la désirabilité sans écrire une ligne de code.', dur:1.5, who:'Équipe produit', out:'Scénario à montrer aux utilisateurs'},
 {id:'prd', name:'PRD one-pager', phase:'conception', fit:[0,1,3,3,3], goals:['align','design'], triggers:['kickoff','misalign'],
  desc:'Problème, objectif, métriques, périmètre, user stories, hors périmètre, questions ouvertes. Une page.',
  why:'Dès que l\'équipe qui construit n\'est plus celle qui a décidé, il faut un document de référence court.', dur:2, who:'PM rédige, équipe relit', out:'PRD validé'},
 // Alignement & delivery
 {id:'raci', name:'RACI', phase:'alignement', fit:[0,1,2,3,3], goals:['align'], triggers:['misalign','slow','kickoff'],
  desc:'Pour chaque activité : Responsable, Approbateur, Consulté, Informé.',
  why:'Les blocages en scale-up viennent de décisions à trois approbateurs ou à aucun.', dur:1.5, who:'Leads concernés', out:'Matrice RACI validée'},
 {id:'daci', name:'DACI (cadre de décision)', phase:'alignement', fit:[0,1,2,3,3], goals:['align'], triggers:['misalign'],
  desc:'Driver, Approver, Contributors, Informed, plus les options étudiées et la décision prise. Un document par décision importante.',
  why:'Plus léger que le RACI : il se remplit décision par décision et garde la trace du pourquoi.', dur:1, who:'Driver + approver', out:'Décision documentée'},
 {id:'dependencies', name:'Carte des dépendances inter-équipes', phase:'alignement', fit:[0,0,1,3,3], goals:['align','process'], triggers:['slow','misalign'], minTeam:16,
  desc:'Chaque équipe, ce qu\'elle attend des autres et quand. Les flèches croisées sont les risques.',
  why:'La delivery ralentit rarement à cause d\'une équipe, mais de ce qu\'elle attend des autres.', dur:2, who:'Un représentant par équipe', out:'Dépendances datées, risques nommés'},
 {id:'pi', name:'PI Planning (SAFe)', phase:'alignement', fit:[0,0,0,3,3], goals:['align','prio'], triggers:['slow','misalign'], minTeam:16,
  desc:'Deux jours où toutes les équipes du train planifient l\'incrément, exposent leurs dépendances et s\'engagent.',
  why:'Passé quatre ou cinq équipes sur le même produit, une synchronisation trimestrielle formelle devient nécessaire.', dur:14, who:'Toutes les équipes du train', out:'Objectifs de PI + program board'},
 {id:'program', name:'Program board', phase:'alignement', fit:[0,0,0,3,3], goals:['align'], triggers:['slow'], minTeam:16,
  desc:'Sprints en colonnes, équipes en lignes, features et dépendances reliées par des fils.',
  why:'La sortie du PI Planning : la vue partagée des dépendances entre équipes sur le trimestre.', dur:2, who:'RTE + PO', out:'Board de programme à jour'},
 {id:'premortem', name:'Pre-mortem', phase:'alignement', fit:[1,2,3,3,3], goals:['align'], triggers:['kickoff','refonte'],
  desc:'"Nous sommes dans six mois, le projet a échoué. Pourquoi ?" Chacun écrit, on regroupe, on prévient.',
  why:'L\'exercice le plus rentable avant un gros chantier : il autorise à dire les risques que personne n\'ose nommer.', dur:1, who:'Équipe projet + sponsor', out:'Top risques + parades'},
 {id:'launch', name:'Plan de lancement / go-to-market', phase:'alignement', fit:[0,2,3,3,3], goals:['align','measure'], triggers:['kickoff','growth'],
  desc:'Cible, message, canaux, séquence, responsables, métriques de lancement, plan de support.',
  why:'Une feature livrée sans lancement n\'existe pas. Le plan aligne produit, marketing, ventes et support.', dur:2, who:'Produit, marketing, ventes, support', out:'Checklist de lancement datée'},
 {id:'sync', name:'Rituel de synchro stakeholders', phase:'alignement', fit:[0,1,2,3,3], goals:['align'], triggers:['misalign'],
  desc:'Ordre du jour fixe, décisions, actions, points bloquants. Le même format chaque fois.',
  why:'Un désalignement chronique se soigne par un rituel régulier, pas par un atelier ponctuel.', dur:1, who:'PM + stakeholders clés', out:'Compte-rendu partagé, décisions tracées'},
 // Mesure & amélioration continue
 {id:'retro-ssc', name:'Rétro Start / Stop / Continue', phase:'mesure', fit:[1,2,3,3,3], goals:['process'], triggers:['slow'],
  desc:'Trois colonnes, un vote, trois actions maximum.',
  why:'La rétro la plus simple à tenir dans la durée. Le format compte moins que la régularité.', dur:1, who:'Équipe', out:'3 actions avec responsable'},
 {id:'retro-4l', name:'Rétro 4L', phase:'mesure', fit:[1,2,3,3,3], goals:['process'], triggers:['slow'],
  desc:'Liked, Learned, Lacked, Longed for.',
  why:'Variante qui fait remonter les apprentissages, utile après une release ou un incident.', dur:1, who:'Équipe', out:'Apprentissages + actions'},
 {id:'retro-sailboat', name:'Rétro Sailboat', phase:'mesure', fit:[1,2,3,3,3], goals:['process'], triggers:['slow','misalign'],
  desc:'Le vent, les ancres, les rochers, l\'île : ce qui pousse, freine, menace, et l\'objectif.',
  why:'La métaphore aide une équipe fatiguée des rétros à reparler de l\'objectif.', dur:1.25, who:'Équipe', out:'Freins nommés + actions'},
 {id:'health', name:'Team Health Monitor', phase:'mesure', fit:[0,1,2,3,3], goals:['process','align'], triggers:['slow','misalign'],
  desc:'Huit attributs (leadership, valeur, vélocité, dépendances…) notés vert, jaune, rouge par l\'équipe, suivis dans le temps.',
  why:'Le diagnostic qui dit quel atelier faire ensuite : un rouge sur "dépendances" appelle une carte des dépendances, pas une rétro de plus.', dur:1, who:'Équipe', out:'Bilan de santé + 1 action ciblée'},
 {id:'postmortem', name:'Post-mortem sans blâme', phase:'mesure', fit:[0,1,2,3,3], goals:['process'], triggers:['slow'],
  desc:'Chronologie, causes, ce qui a bien marché, actions. Sans nommer de coupable.',
  why:'Après un incident ou un lancement raté, la seule façon d\'apprendre sans que les gens se protègent.', dur:1.5, who:'Impliqués + un facilitateur neutre', out:'Rapport + actions'},
 {id:'metrics', name:'Revue métriques (AARRR)', phase:'mesure', fit:[0,2,3,3,3], goals:['measure'], triggers:['growth'],
  desc:'Acquisition, activation, rétention, revenu, recommandation : où le funnel fuit.',
  why:'Avant de chercher un nouveau levier de croissance, mesurer où l\'on perd les utilisateurs existants.', dur:2, who:'Produit, data, growth', out:'Étape de funnel prioritaire'},
 {id:'ia', name:'Inspect & Adapt (SAFe)', phase:'mesure', fit:[0,0,0,3,3], goals:['process'], triggers:['slow'], minTeam:16,
  desc:'Démo de l\'incrément, mesures, atelier de résolution de problèmes à l\'échelle du train.',
  why:'La rétro d\'un train de release : les problèmes systémiques ne se règlent pas dans une rétro d\'équipe.', dur:4, who:'Toutes les équipes du train', out:'Amélioration systémique planifiée'},
];


// Fichier FigJam communautaire : rempli par le générateur (clé du fichier + node-id de la section de chaque atelier)
const FIGJAM = { file: 'zhiQxgTHsZlPgmD1d6tjKl', name: 'Boussole-Ateliers', nodes: {"kickoff":"3:2","problem":"3:59","stakeholders":"3:110","charter":"3:164","lean":"3:242","bmc":"3:303","vpc":"4:194","vision":"4:245","impact":"4:286","box":"4:393","positioning":"4:428","nsm":"4:482","okr":"5:399","horizons":"5:443","prfaq":"5:495","persona":"5:516","jtbd":"5:573","empathy":"5:614","journey":"6:531","research-plan":"6:553","assumptions":"6:594","ost":"6:648","blueprint":"6:779","kano":"6:851","hmw":"7:728","mindmap":"7:780","affinity":"7:886","crazy8":"7:961","brainwriting":"7:973","dotvote":"7:993","sprint":"8:889","experiments":"8:928","impact-effort":"8:996","rice":"8:1050","moscow":"8:1090","storymap":"8:1153","roadmap":"9:1061","nnl":"9:1105","decision":"9:1165","wsjf":"9:1193","sprintplan":"9:1233","sitemap":"9:1288","wireframes":"10:1210","userflow":"10:1220","storyboard":"10:1267","prd":"10:1281","raci":"10:1296","daci":"10:1330","dependencies":"11:1264","pi":"11:1322","program":"11:1346","premortem":"11:1418","launch":"11:1478","sync":"11:1519","retro-ssc":"12:1417","retro-4l":"12:1469","retro-sailboat":"12:1524","health":"12:1574","postmortem":"12:1613","metrics":"12:1676","ia":"12:1715"} };

if (typeof module !== 'undefined') module.exports = { STAGES, TEAMS, TRIGGERS, GOALS, HORIZONS, PHASES, T, FIGJAM };
