// Workshop Compass: canonical URL for each how-to source (key = template id).
const SOURCES = {
  persona:      'https://www.cooper.com/journal/2008/05/the_origin_of_personas/',
  bmc:          'https://www.strategyzer.com/library/the-business-model-canvas',
  vpc:          'https://www.strategyzer.com/library/the-value-proposition-canvas',
  prfaq:        'https://workingbackwards.com/',
  nsm:          'https://amplitude.com/north-star',
  positioning:  'https://www.aprildunford.com/obviously-awesome',
  lean:         'https://leanstack.com/lean-canvas',
  daci:         'https://www.atlassian.com/team-playbook/plays/daci',
  health:       'https://www.atlassian.com/team-playbook/health-monitor',
  starfish:     'https://www.thekua.com/rant/2006/03/the-retrospective-starfish/',
  horizons:     'https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/enduring-ideas-the-three-horizons-of-growth',
  brainwriting: 'https://en.wikipedia.org/wiki/6-3-5_Brainwriting',
  jtbd:         'https://jobs-to-be-done.com/',
  moscow:       'https://en.wikipedia.org/wiki/MoSCoW_method',
  empathy:      'https://gamestorming.com/empathy-mapping/',
  metrics:      'https://www.slideshare.net/dmc500hats/startup-metrics-for-pirates-long-version',
  assumptions:  'https://www.strategyzer.com/library/assumptions-mapping',
  wsjf:         'https://scaledagileframework.com/wsjf/',
  experiments:  'https://leanstack.com/',
  blueprint:    'https://www.nngroup.com/articles/service-blueprints-definition/',
  premortem:    'https://hbr.org/2007/09/performing-a-project-premortem',
  impact:       'https://www.impactmapping.org/',
  rice:         'https://www.intercom.com/blog/rice-simple-prioritization-for-product-managers/',
  crazy8:       'https://designsprintkit.withgoogle.com/methodology/phase3-sketch/crazy-8s',
  altworlds:    'https://www.luma-institute.com/alternative-worlds/',
  radar:        'https://www.luma-institute.com/whats-on-your-radar/',
  sprint:       'https://www.thesprintbook.com/',
  storymap:     'https://www.jpattonassociates.com/story-mapping/',
  affinity:     'https://en.wikipedia.org/wiki/Affinity_diagram',
  okr:          'https://www.whatmatters.com/',
  box:          'https://www.innovationgames.com/product-box/',
  kano:         'https://en.wikipedia.org/wiki/Kano_model',
  hmw:          'https://designsprintkit.withgoogle.com/methodology/phase1-understand/how-might-we',
  vision:       'https://www.romanpichler.com/tools/product-vision-board/',
  pi:           'https://scaledagileframework.com/pi-planning/',
  program:      'https://scaledagileframework.com/pi-planning/',
  ia:           'https://scaledagileframework.com/inspect-and-adapt/',
  sprintplan:   'https://scrumguides.org/scrum-guide.html',
  ost:          'https://www.producttalk.org/opportunity-solution-tree/',
  mindmap:      'https://en.wikipedia.org/wiki/Mind_map',
  poker:        'https://en.wikipedia.org/wiki/Planning_poker',
  tshirt:       'https://www.agilealliance.org/glossary/estimation/',
  buyfeature:   'https://www.lukehohmann.com/innovation-games/buy-a-feature',
  remember:     'https://www.lukehohmann.com/innovation-games/remember-the-future',
  eventstorming:'https://www.eventstorming.com/',
  vsm:          'https://www.lean.org/lexicon-terms/value-stream-mapping/',
  roam:         'https://scaledagileframework.com/pi-planning/',
  teamboard:    'https://scaledagileframework.com/pi-planning/',
  refinement:   'https://scrumguides.org/scrum-guide.html',
  dod:          'https://scrumguides.org/scrum-guide.html',
  storywriting: 'https://www.agilealliance.org/glossary/invest/',
  teamcanvas:   'https://theteamcanvas.com/',
  pitch:        'https://www.aprildunford.com/obviously-awesome',
};
if (typeof module !== 'undefined') module.exports = { SOURCES };
